### ISSUE TITLE
Exception at rule 'ToCharInOrderBy'

### ISSUE THREAD

**Issue by khirzer** [felipebz/sonar-plsql#106]
Hi Felipe,

I've noticed that in a very special case an exception is thrown at rule 'ToCharInOrderBy':

    function test (testcol in number) return varchar2 is
    begin
      select testcol
        from table
       where tabcolumn = 'test'
       order by testcol;
    end;

Exception:

    java.lang.NumberFormatException: For input string: "testcol"

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.sonar.plsqlopen.checks.ToCharInOrderByCheck.visitNode(ToCharInOrderByCheck.java:61)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitNode(PlSqlAstWalker.java:103)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:69)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visitChildren(PlSqlAstWalker.java:83)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.visit(PlSqlAstWalker.java:71)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.walk(PlSqlAstWalker.java:60)
	at org.sonar.plsqlopen.checks.verifier.PlSqlCheckVerifier.scanFileForIssues(PlSqlCheckVerifier.java:51)
	at org.sonar.plsqlopen.checks.verifier.PlSqlCheckVerifier.getActualIssues(PlSqlCheckVerifier.java:127)
	at org.sonar.plsqlopen.checks.verifier.PlSqlCheckVerifier.verify(PlSqlCheckVerifier.java:64)
	at org.sonar.plsqlopen.checks.verifier.PlSqlCheckVerifier.verify(PlSqlCheckVerifier.java:56)
	at org.sonar.plsqlopen.checks.ToCharInOrderByCheckTest.test(ToCharInOrderByCheckTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Thanks!
Karl

**Comment by felipebz** [comment]
Thanks @khirzer!
