### ISSUE TITLE
Custom Rule: Not a valid line offset for pointer

### ISSUE THREAD

**Issue by khirzer** [felipebz/sonar-plsql#77]
Hi!

I've implemented a very simple custom rule based on snapshot version 2.2.0 (with version 2.1.0 this rule works):

    @Override
    public void init() {
        subscribeTo(GenericTokenType.EOF);
    }

    @Override
    public void visitNode(AstNode node) {
        if (!node.getPreviousAstNode().is(PlSqlGrammar.EXECUTE_PLSQL_BUFFER)) {
            addIssue(node, "There must be a slash at the end of file");
        }
    }

This is the test file content:

    create or replace package body Test is

    end Test;

When I execute an analysis with SonarQube scanner I get the following exception:

    ERROR: Error during SonarQube Scanner execution
    java.lang.IllegalArgumentException: 12 is not a valid line offset for pointer. File plsql/Test.pkb has 9 character(s) at line 3
        at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:312)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:246)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:262)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.newLocation(PlSqlAstScanner.java:189)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.saveIssues(PlSqlAstScanner.java:172)
        at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanFile(PlSqlAstScanner.java:142)
        at org.sonar.plsqlopen.PlSqlSquidSensor.execute(PlSqlSquidSensor.java:101)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

Do I have to change my rule for version 2.2.0 or do you intend to change the relevant source code?

Thank you!

**Comment by felipebz** [comment]
Hi @khirzer.

Thanks for raising this issue. I could reproduce the issue with the code you shared. It's definitely a bug that I need to look into.

**Comment by felipebz** [comment]
@khirzer, what's your SonarQube version?

> with version 2.1.0 this rule works

I found out that SonarQube >=7.3 isn't executing the custom rules with the version 2.1.0 of this plugin (this bug is already fixed in 2.2.0). Maybe this is the reason that the rule _seems to be working_ with the older version.

With SonarQube 7.2.1 and sonar-plsql-open-plugin 2.1.0 I get:

```
java.lang.IllegalArgumentException: 3 is not a valid line offset for pointer. File test.sql has 0 character(s) at line 5
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:312)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:246)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:262)
	at org.sonar.plsqlopen.PlSqlIssue.setPrimaryLocation(PlSqlIssue.java:55)
	at org.sonar.plsqlopen.PlSqlSquidSensor.reportIssue(PlSqlSquidSensor.java:145)
	at org.sonar.plsqlopen.PlSqlSquidSensor.execute(PlSqlSquidSensor.java:106)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	(...)
```

And, looking again to your validation, I see that you're using "addIssue" to register the issue. This method will take the "start" and "end" position of the node (in your case, the EOF token) and try to register an issue in this location. It looks like that SonarQube doesn't consider the EOF as a valid position, raising that exception above.

Therefore: to fix your issue, I suggest to change the addIssue call to:

```java
addLineIssue("There must be a slash at the end of file", node.getTokenLine());
```

This will result in:

![image](https://user-images.githubusercontent.com/13829/44374758-561cad80-a4c6-11e8-8c7b-4a9d8d0e760f.png)

**Comment by khirzer** [comment]
Thank you for the quick reply! I'm using SonarQube 7.1.0.

The code of 'visitNode' of my custom rule in version 2.1.0 is

    @Override
    public void visitNode(AstNode node) {
        if (!node.getPreviousAstNode().is(PlSqlGrammar.EXECUTE_PLSQL_BUFFER)) {
            getContext().createViolation(this, "There must be a slash at the end of file", node);
        }
    }

Now I'm using 'addLineIssue' in version 2.2.0 and the rule works fine. Thank you for your help!

**Comment by sabrimev** [comment]
Faced this issue also. As I copied some code from macbook notes app into visual studio mac, this error occurred. Solved by rewriting the same code. 

I think somehow it copies or change some characters at ASCII level or something in the background.
