### ISSUE TITLE
Anchored datatype with null clause gives null pointer exception

### ISSUE THREAD

**Issue by jleendertse** [felipebz/sonar-plsql#91]
The following declaration of a variable gives a null pointer exception:
`var_type    tab.col%type not null;`

15:00:10.472 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at org.sonar.plsqlopen.symbols.DefaultTypeSolver.solve(DefaultTypeSolver.java:45)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.solveType(SymbolVisitor.java:278)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visitVariableDeclaration(SymbolVisitor.java:223)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visitNodeInternal(SymbolVisitor.java:143)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visit(SymbolVisitor.java:126)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visitChildren(SymbolVisitor.java:136)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visit(SymbolVisitor.java:127)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visitChildren(SymbolVisitor.java:136)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visit(SymbolVisitor.java:127)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visitChildren(SymbolVisitor.java:136)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visit(SymbolVisitor.java:127)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visitChildren(SymbolVisitor.java:136)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visit(SymbolVisitor.java:127)
	at org.sonar.plsqlopen.symbols.SymbolVisitor.visitFile(SymbolVisitor.java:82)
	at org.sonar.plsqlopen.squid.PlSqlAstWalker.walk(PlSqlAstWalker.java:62)
	at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanMainFile(PlSqlAstScanner.java:128)
	at org.sonar.plsqlopen.squid.PlSqlAstScanner.scanFile(PlSqlAstScanner.java:99)
	at org.sonar.plsqlopen.PlSqlSquidSensor.execute(PlSqlSquidSensor.java:101)

Could you have a look at it?

**Comment by felipebz** [comment]
Thanks again. ;-)
